### ISSUE TITLE
Project Peer Review Hillary yaory

### ISSUE THREAD

**Issue by hillaryyaory** [hweng1/WebTech_Project#2]
Two technical issues:
No website address in project description, so I couldn’t go directly to your website.

The forms in contact and feedback page are readonly, people can’t actually comment anything.

Two suggestions on content:

The font for the navigation bar is very hard to read. But this is more preference. 

MBTI/ISTP/ENTP page has a lot of small text
The black background and the chunk of white small text makes it very overwhelming and difficult to read, making it hard for visitors to find what they’re looking for. I think it is useful information so you should have it somewhere on your website. Therefore, I think if you were to keep the black background and white text, you should paraphrase it so it’s less wordy and add font size. I also wouldn’t want to scroll down the whole page instead I would prefer having to click buttons for more information (like a dropdown menu for information).

Spelling errors 
There are a few spelling mistakes and grammatical errors.

**Comment by hweng1** [comment]
thanks for the feedback I have fixed some issues
