### ISSUE TITLE
Peer review 

### ISSUE THREAD

**Issue by Asethi01** [hweng1/WebTech_Project#3]
You have done a great job with your website. I have a few suggestions that you may like. 
Content issues: 
1. I think that there is a bit too much content in a very tiny font. It may be better if you had less information but in a bigger font that may be easier to read. 
2. On the personality type pages, it may be better to link a video explaining than having so much text. The pages could benefit from more visual content. 
Technical Issues: 
1. I believe that the placement of the sitemap page link should be at the end of the navigation bar instead of the front because it would give people a chance through your website. 
2. Your home page link is not in all caps, whereas all the other links are. This seems a bit odd, It may be better to change it to make it all look similar.

**Comment by hweng1** [comment]
thanks for the feedback I have fixed some issues
